MovieHouse/MovieHouse/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movie.urls")),
    path('series/',include("series.urls")),
    path('watch/',include('watch.urls')),
    path('search/',include('search.urls'))
]
if settings.DEBUG:urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MovieHouse/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from movie import views
app_name="movie"
urlpatterns = [
    path('',views.base,name="base"),
    path('login/',views.user_login,name="login"),
    path('register/',views.user_register,name="register"),
    path('movie_home/',views.movie_home,name="home"),
    path('details/<m>',views.movie_details,name="details"),
    path('language/<l>',views.movie_language,name="language"),
    path('watch/<int:m>',views.movie_watch,name="watchmovie"),
    path('logout/',views.user_logout,name="logout"),
    path('home/',views.home_all,name="homeall"),
]

MovieHouse/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"
urlpatterns = [
    path('',views.searchresult,name="searchresult"),

]

MovieHouse/series/urls.py
from django.contrib import admin
from django.urls import path,include
from series import views
app_name="series"
urlpatterns = [
    path('series_home/',views.series_home,name="shome"),
    path('details/<int:pk>',views.series_details,name="sdetails"),
    path('view/<int:pk>',views.series_view,name="series"),
    path('episodes/<int:pk>',views.series_episodes,name="episodes")
]

MovieHouse/watch/urls.py
from django.contrib import admin
from django.urls import path
from watch import views
app_name="watch"
urlpatterns = [
    path('add_to_watchlist/<int:pk>',views.add_to_watchlist,name="add_to_watchlist"),
    path('view_watchlist',views.viewwatchlist,name="watchlist_view"),
    path('add_watchlist/<int:pk>',views.add_to_Swatchlist,name="swatchlist"),
    path('Mwatchlist/', views.viewMwatchlist, name="Mwatchlist"),
    path('remove/<int:pk>',views.mremove,name="mremove"),
    path('sremove/<int:pk>', views.sremove, name="sremove"),
    path('subscribe/',views.subscribe,name="subscribe"),
    path('freetrial/',views.freetrial,name="freetrial"),
    path('subscription/',views.subscription,name="subscription"),
    path('annual/', views.subscription2, name="subscription2")

]

MovieHouse/movie/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Genere(models.Model):
    genere=models.CharField(max_length=100)
    def __str__(self):
        return self.genere
class Language(models.Model):
    language=models.CharField(max_length=100)

    def __str__(self):
        return self.language

class Movie(models.Model):
    mname=models.CharField(max_length=100)
    image=models.ImageField(upload_to="movie/movies",blank=True,null=True)
    year=models.CharField(max_length=50)
    duration=models.CharField(max_length=100)
    rating_outof_10=models.IntegerField()
    cover=models.ImageField(upload_to="movies/cover",blank=True,null=True)
    description=models.TextField()
    genere=models.ForeignKey(Genere,on_delete=models.CASCADE)
    trending=models.BooleanField(default=False)
    language=models.ForeignKey(Language,on_delete=models.CASCADE)
    video=models.FileField(upload_to="movies/videos",max_length=500)
    status=models.CharField(max_length=100)
    def __str__(self):
        return self.mname

MovieHouse/movie/views.py
from django.shortcuts import render,redirect
from movie.models import Movie,Genere,Language
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from series.models import Series
from watch.models import Freetrial,Subscribe
from django.contrib.auth.decorators import login_required
# Create your views here.
def base(request):
    user=request.user
    if(user.is_authenticated):
        return redirect('movie:homeall')
    return render(request,'basic.html')
def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('movie:homeall')
        else:
            messages.error(request, "Invalid credentials ")
            return render(request, 'login.html')
    return render(request,'login.html')
def user_register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        p1=request.POST['p1']
        e=request.POST['e']
        if(p==p1):
            try:
                u=User.objects.create_user(username=u,password=p,email=e)
                u.save()
                m=" Successfully registered now please "
                return render(request,'register.html',{'m':m})
            except:
                messages.error(request, "The username is already taken ")
                return render(request, 'register.html')
        else:
            messages.error(request, "please check your password")
            return render(request, 'register.html')
    return render(request,'register.html')
@login_required
def movie_home(request):
    m=Movie.objects.filter(trending=True)
    a=Movie.objects.filter(genere__genere__icontains="action")
    b=Movie.objects.filter(genere__genere__icontains="drama")
    c=Movie.objects.filter(genere__genere__icontains="comedy")
    d=Movie.objects.filter(genere__genere__icontains="thriller")
    return render(request,'home.html',{'m':m,'a':a,'b':b,'c':c,'d':d})
@login_required
def movie_details(request,m):
    m=Movie.objects.get(mname=m)
    return render(request,'details.html',{'m':m})
@login_required
def movie_language(request,l):
    m=Movie.objects.filter(language__language=l)
    s=Series.objects.filter(language=l)
    return render(request,'language.html',{'l':m,'s':s})
@login_required
def movie_watch(request,m):
    m=Movie.objects.get(id=m)
    user=request.user
    try:
        f = Freetrial.objects.filter(user=user)
        s = Subscribe.objects.filter(user=user)
        if (f):
            return render(request, 'movie.html', {'m': m})
        elif(s):
            return render(request, 'movie.html', {'m': m})
        else:
            return redirect('watch:subscribe')
    except:
       return redirect('watch:subscribe')



@login_required
def user_logout(request):
    logout(request)
    return redirect('movie:login')
@login_required
def home_all(request):
    m=Movie.objects.all()
    s=Series.objects.all()
    return render(request,'homeall.html',{'s':s,'m':m})

MovieHouse/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie House</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Gabarito:wght@700&family=Inter:wght@300&family=Merriweather:wght@700&family=Oswald:wght@500&family=Playfair+Display:ital,wght@1,500&family=Poppins:ital,wght@0,200;0,300;0,900;1,500&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;700&family=Roboto:ital,wght@0,400;1,300;1,400&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Inter:wght@300&family=Oswald:wght@500&family=Playfair+Display:wght@600&family=Poppins:wght@200;300&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;600&family=Roboto:ital,wght@0,400;1,300&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Inter:wght@300&family=Oswald:wght@500&family=Playfair+Display:wght@600&family=Poppins:wght@200;300&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab&family=Roboto:ital,wght@0,400;1,300&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Gabarito:wght@700&family=Inter:wght@300&family=Oswald:wght@500&family=Playfair+Display:wght@600&family=Poppins:wght@200;300;900&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;600&family=Roboto:ital,wght@0,400;1,300&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Gabarito:wght@700&family=Inter:wght@300&family=Oswald:wght@500&family=Playfair+Display:wght@600&family=Poppins:ital,wght@0,200;0,300;0,900;1,500&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;600&family=Roboto:ital,wght@0,400;1,300&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Gabarito:wght@700&family=Inter:wght@300&family=Oswald:wght@500&family=Playfair+Display:ital,wght@1,500&family=Poppins:ital,wght@0,200;0,300;0,900;1,500&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;600&family=Roboto:ital,wght@0,400;1,300&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Gabarito:wght@700&family=Inter:wght@300&family=Oswald:wght@500&family=Playfair+Display:ital,wght@1,500&family=Poppins:ital,wght@0,200;0,300;0,900;1,500&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;600&family=Roboto:ital,wght@0,400;1,300;1,400&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=DM+Sans:opsz,wght@9..40,300&family=Gabarito:wght@700&family=Inter:wght@300&family=Merriweather:wght@700&family=Oswald:wght@500&family=Playfair+Display:ital,wght@1,500&family=Poppins:ital,wght@0,200;0,300;0,900;1,500&family=Roboto+Condensed:ital,wght@1,600&family=Roboto+Slab:wght@400;600&family=Roboto:ital,wght@0,400;1,300;1,400&family=Slabo+27px&family=Tektur&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<header>
  <div>
    <div>
      <nav class="navbar navbar-expand-xl navbar-dark ">
        <div class="container-fluid">
          <h2 class="navbar-brand mt-1" style="font-family: 'Roboto Slab', serif;">Movie House</h2>
          <button   class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span  class="navbar-toggler-icon"></span>
          </button>
            {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'movie:homeall' %}">Home</a>
              </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Category
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item  " href="{% url 'movie:home' %}"><span style="text-transform:capitalize; font-size:15px;">Movies</span></a></li>
                        <li><a class="dropdown-item" href="{% url 'series:shome' %}"><span style="text-transform:capitalize; font-size:15px;">Series</span></a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Language
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                        {% for i in links %}
                        <li><a class="dropdown-item " href="{% url 'movie:language' i.language %}"><span style="text-transform:capitalize; font-size:15px;">{{i.language}}</span></a></li>
                        {% endfor %}
                    </ul>
                </li>
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-bookmark" style="color: #ffffff;"></i> Watchlist
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item  " href="{% url 'watch:Mwatchlist' %}"><span style="text-transform:capitalize; font-size:15px;">Movies</span></a></li>
                        <li><a class="dropdown-item  " href="{% url 'watch:watchlist_view' %}"><span style="text-transform:capitalize; font-size:15px;">Series</span></a></li>
                    </ul>
                </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'movie:logout' %}">Log out</a>
              </li>
              <li class="nav-item  ms-2 ">
                  <a class="nav-link active  ms-0 fs-5 " href="{% url 'watch:subscribe' %}" style="color:#61c467">Subscription</a>
              </li>
            </ul>
            <form class="d-flex" method="POST" action="{% url 'search:searchresult' %}">
                {% csrf_token %}
              <input class="form-control me-2 " type="search"  name="q" placeholder="Search" aria-label="Search">
              <button class="btn btn-danger search " type="submit">Search</button>
            </form>
            <div class="ms-2 pt-3 pe-2 ps-3 name ">
            <p class="me-1 ms-2 " style="font-size:15px;text-transform:uppercase;color:white;"><i class="fa-regular fa-user " style="font-size:16px;color:white;"></i> {{user.username}}</p>
            </div>
                              {% endif %}
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>
<body>
{% block content %}
{% endblock %}
</body>
</html>

MovieHouse/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="margin-bottom:50px;">
    <div>
        <div class="cover">
            <img src="{{m.cover.url}}" height="669px" width="100%">
        </div>
        <div class="cover-text text-light fw-light">
            <h2 class="ms-5 " style="font-family: 'Merriweather', serif;"><strong>{{m.mname}}<span class="fs-4">({{m.language}})</span></strong></h2>
            <p class="fs-5 ms-2 mt-3 "><i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>IMDb {{m.rating_outof_10}}/10 </span>
              &nbsp; <i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>{{m.language}}</span>   &nbsp; <i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>{{m.year}}</span>
             &nbsp; <i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>{{m.genere}}</span></p>
            <p class="fs-5 mt-1 ms-2">{{m.description}}</p>
            {% if m.status == "Coming Soon" %}
            <h2 class="fs-3 text-center ">Coming Soon</h2>
            <div class="mt-5 ms-5">
                <a href="{% url 'movie:watchmovie' m.id %}" class="btn btn-light btn-lg text-black ms-1 me-1 "><i class="fa-solid fa-play fa-sm" style="color:black;"></i> Watch Trailer</a>
                &nbsp; <a href="{% url 'watch:add_to_watchlist' m.id %}" class="btn btn-light btn-lg text-black ms-1 me-1 "><i class="fa-solid fa-plus 1" style="color:black;"></i> add to watchlist </a>
            </div>
            {% else %}
             <div class="mt-5 ms-5">
                <a href="{% url 'movie:watchmovie' m.id %}" class="btn btn-light btn-lg text-black ms-1 me-1 "><i class="fa-solid fa-play fa-sm" style="color:black;"></i> Watch now</a>
                &nbsp; <a href="{% url 'watch:add_to_watchlist' m.id %}" class="btn btn-light btn-lg text-black ms-1 me-1 "><i class="fa-solid fa-plus 1" style="color:black;"></i> add to watchlist </a>
            </div>
            {% endif %}


        </div>
    </div>
</div>
{% endblock %}

MovieHouse/templates/episodes.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ms-5">
    <div class="mt-1" style="margin-bottom:50px;">
                <h2><strong>Episodes</strong></h2>
                <div class="mt-2">
                    {% for i in range %}
                    <div  class="mt-2 " style="height:50px; width:50%; border:2px solid blue;border-radius:30px;">
                        <div class="m-2">
                            <div class="ms-3 mt-1">
                                <p><strong>{{s.sname}} episode {{i}} <a  style="margin-left:200px; display:inline;" href="{% url 'series:series' s.id %}" class="btn btn-info mt-2">watch now <i class="fa-solid fa-play fa-sm" style="color:blue;"></i></a></strong></p><p style="display:block;">
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
    </div>
</div>
{% endblock %}

MovieHouse/templates/freetrial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

MovieHouse/templates/homeall.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  <div class="m-5">
    <div class="m-3">
      <h2 class="ms-3" style="font-family: 'Roboto Slab', serif; border-bottom:2px solid black;">Movies</h2>
      <div class="row">
                {% for i in m %}
                <div class="col-sm-2 mt-1">
                    <div class="card bg-info m-2">
                        <img src="{{i.image.url}}" height="250px" width="250px" class="card-img-top" alt="...">
                            <a href="{% url 'movie:details' i.mname %}" style="font-family: 'Roboto Slab', serif;" class="btn btn-info ">Watch now</a>
                    </div>
                </div>
                {% endfor %}
            </div>
      <h2 class="ms-3 mt-3" style="font-family: 'Roboto Slab', serif; border-bottom:2px solid black;">Series</h2>
      <div class="row">
                {% for i in s %}
                <div class="col-sm-2 mt-1">
                    <div class="card bg-info m-2">
                        <img src="{{i.image.url}}" height="250px" width="250px" class="card-img-top" alt="...">
                            <a href="{% url 'series:sdetails' i.id %}" style="font-family: 'Roboto Slab', serif;" class="btn btn-info ">Watch now</a>
                    </div>
                </div>
                {% endfor %}
            </div>
    </div>
  </div>

</div>
{% endblock %}

MovieHouse/templates/language.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="margin-top:20px;margin-bottom:80px;">
    <div class="ms-5 me-5">
            <div class="row">
                {% for i in l %}
                <div class="col-sm-2 mt-3">
                    <div class="card bg-info ">
                        <img src="{{i.image.url}}" height="250px" width="250px" class="card-img-top" alt="...">
                            <a href="{% url 'movie:details' i.mname %}" style="font-family: 'Roboto Slab', serif;" class="btn btn-info ">Watch now</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        <div class="row">
                {% for i in s %}
                <div class="col-sm-2 mt-3">
                    <div class="card bg-info ">
                        <img src="{{i.image.url}}" height="250px" width="250px" class="card-img-top" alt="...">
                            <a href="{% url 'series:sdetails' i.id %}" style="font-family: 'Roboto Slab', serif;" class="btn btn-info ">Watch now</a>
                    </div>
                </div>
                {% endfor %}
            </div>

</div>
</div>
{% endblock %}

MovieHouse/templates/movie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  <div>
     <video  autoplay controls>
      <source src="{{m.video.url}}" type="video/mp4">
      Your browser does not support HTML video.
    </video>
      </div>
  </div>
{% endblock %}

MovieHouse/templates/sdetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div>
        <div class="cover">
             <div>
             <img src="{{s.image.url}}" height="669px" width="100%">
            </div>
        </div>
        <div class="cover-text text-light fw-light">
            <h2 class="ms-5 " style="font-family: 'Merriweather', serif;"><strong>{{s.sname}}</strong></h2>
            <p class="fs-5 ms-2 mt-3 "><i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>IMDb {{s.rating_outof_10}}/10 </span>
              &nbsp; <i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>{{s.language}}</span>
             &nbsp; <i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span> Episodes : {{s.no_of_episodes}}</span></p>
            <p class="fs-5 mt-1 ms-2">{{s.description}}</p>
            <div class="mt-5 ms-5">
                <a href="{% url 'series:episodes' s.id %}" class="btn btn-light btn-lg text-black ms-1 me-1 "><i class="fa-solid fa-play fa-sm" style="color:black;"></i> Watch now</a>
                &nbsp; <a href="{% url 'watch:swatchlist' s.id %}" class="btn btn-light btn-lg text-black ms-1 me-1 "><i class="fa-solid fa-plus 1" style="color:black;"></i> add to watchlist </a>

            </div>
        </div>
 </div>

{% endblock %}

MovieHouse/templates/shome.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-4">
     <div class="row">
                {% for i in s %}
                <div class="col-sm-2 mt-1">
                    <div class="card bg-info">
                        <img src="{{i.image.url}}" height="250px" width="250px" class="card-img-top" alt="...">
                            <a href="{% url 'series:sdetails' i.id%}" style="font-family: 'Roboto Slab', serif;" class="btn btn-info ">{{i.sname}}</a>
                    </div>
                </div>
                {% endfor %}
     </div>
</div>
{% endblock %}

MovieHouse/templates/subscribeconfirm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" >
    <h3 class="text-center text-success">{{msg}}</h3>
    <h3 class="text-center text-danger">Thank you...</h3>
    <p class="text-center"><a href="{% url 'movie:homeall' %}">return to home</a></p>
</div>
{% endblock %}

MovieHouse/templates/watchlist.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
 <div class="m-4 mb-5">
    {% if  not s %}
    <div>
        <h4 class="text-center"> The Watchlist Is Empty. Return to  <a href="{% url 'movie:homeall' %}"> Home Page </a></h4>
    </div>
    {% else %}
     <div  style="height:200px; width:100%; margin-top:60px;  margin-bottom: 25px;">
        {% for i in s %}
        <div class="row border-bottom border-5 border-dark">
            <div class="col-sm-2 mt-2 mb-2" >
                <img src="{{i.series.image.url}}" height="200px" width="100%"  >
            </div>
            <div class="col-sm-10 ">
                <h2 class="ms-4 " style="font-family: 'Merriweather', serif;"><strong>{{i.series.sname}}</strong></h2>
                <p class="fs-5 ms-2 mt-1 "><i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>IMDb {{i.series.rating_outof_10}}/10 </span>
                    &nbsp;<i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span>{{i.series.language}}</span>
                    &nbsp;<i class="fa-solid fa-circle fa-sm " style="color:orange;font-size:6px;"></i> <span> Episodes : {{i.series.no_of_episodes}}</span></p>
                <p class="fs-5  ms-2">{{i.series.description}}</p>
                <div class=" ms-5 mb-5 text-light" >
                    <a href="{% url 'series:episodes' i.series.id %}" class="btn btn-dark btn-md "><i class="fa-solid fa-play fa-sm" style="color:white;"></i> Watch now</a>
                    &nbsp; <a href="{% url 'watch:sremove' i.id %}" class="btn btn-dark btn-md   "> Remove </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
     {% endif %}
</div>
</div>
    {% endblock %}